spring.application.name=url-shortner

spring.datasource.url=jdbc:postgresql://postgres:5432/shortner
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

## Optional (debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.open-in-view=false

## App Config
app.base-url=http://localhost:8080
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10


#spring.data.web.pageable.one-indexed-parameters=true